/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    CandidateSingleSelectTable: typeof import('./src/components/CandidateSingleSelectTable.vue')['default']
    Chip: typeof import('primevue/chip')['default']
    DashboardTable: typeof import('./src/components/DashboardTable.vue')['default']
    FilesUploader: typeof import('./src/components/FilesUploader.vue')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Navbar: typeof import('./src/components/navbar/Navbar.vue')['default']
    NavbarBody: typeof import('./src/components/navbar/NavbarBody.vue')['default']
    NavbarFooter: typeof import('./src/components/navbar/NavbarFooter.vue')['default']
    NavbarGroup: typeof import('./src/components/navbar/NavbarGroup.vue')['default']
    NavbarHeader: typeof import('./src/components/navbar/NavbarHeader.vue')['default']
    NewCandidacyStepper: typeof import('./src/components/NewCandidacyStepper.vue')['default']
    NewCandidateModal: typeof import('./src/components/new-candidate/NewCandidateModal.vue')['default']
    NewJobStepper: typeof import('./src/components/NewJobStepper.vue')['default']
    PageForm: typeof import('./src/components/PageForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('primevue/sidebar')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SkillsList: typeof import('./src/components/SkillsList.vue')['default']
    Slider: typeof import('primevue/slider')['default']
    Textarea: typeof import('primevue/textarea')['default']
  }
}
