steps:
 # Build the server container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--platform linux/amd64', '-t',
    'asia-southeast1-docker.pkg.dev/recruiter-420314/recruiter-registry/recruiter-api',
    '-f', 'server/Dockerfile', '.']

# Build the client container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--platform linux/amd64', '-t',
    'asia-southeast1-docker.pkg.dev/recruiter-420314/recruiter-registry/recruiter-client',
    '--build-arg', 'VITE_API_ORIGIN=https://recruiter-api-yklq5atc4q-ew.a.run.app',
    '--build-arg', 'VITE_API_PATH=/api/v1',
    '-f', 'client/Dockerfile', '.']

# Push the server container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-southeast1-docker.pkg.dev/recruiter-420314/recruiter-registry/recruiter-api']
# Push the client container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-southeast1-docker.pkg.dev/recruiter-420314/recruiter-registry/recruiter-client']

# Deploy server container to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'recruiter-api',
    '--image', 'asia-southeast1-docker.pkg.dev/recruiter-420314/recruiter-registry/recruiter-api',
    '--region', 'europe-west1',
    '--allow-unauthenticated']

# Deploy client container to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'recruiter-client',
    '--image', 'asia-southeast1-docker.pkg.dev/recruiter-420314/recruiter-registry/recruiter-client',
    '--region', 'europe-west1',
    '--allow-unauthenticated']

options:
  logging: CLOUD_LOGGING_ONLY
