version: '3.8'

services:
  database:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recruiter
    ports:
      - "5435:5432"
    volumes:
      - recruiter-db:/var/lib/postgresql/data

  server:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/recruiter
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "3000:3000"
    depends_on:
      - database

  client:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
        VITE_API_ORIGIN: http://localhost:3001
        VITE_API_PATH: /api/v1
    environment:
      API_PROXY_PASS: http://server:3000
    ports:
      - "3001:80"
    depends_on:
      - server

volumes:
  recruiter-db:
