version: '3.8'

services:
  database:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recruiterdb
    ports:
      - "5435:5432"
    volumes:
      - recruiter-db:/var/lib/postgresql/data

  server:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./server/Dockerfile
      image: recruiter-server:latest
    env_file:
      - ./server/src/main/resources/application.yml
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: vilnius4kids
      DB_SSL: false
      DB_HOST: database
    ports:
      - "3000:3000"
    depends_on:
      - database

  client:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./client/Dockerfile
      image: recruiter-client:latest
      args:
        VITE_API_ORIGIN: http://localhost:3001
        VITE_API_PATH: /api/v1/trpc
    environment:
      API_PROXY_PASS: http://server:3000
    ports:
      - "3001:80"
    depends_on:
      - server

volumes:
  vilnius4kids-db:
