server:
    port: ${SERVER_PORT}
    error:
        include-message: always

google:
    storage:
        bucket:
            name: ${GOOGLE_CLOUD_BUCKET_NAME}
        project:
            id: ${GOOGLE_CLOUD_PROJECT_ID}

password:
    reset:
        token:
            expirationInSeconds: ${RESET_PASSWORD_TOKEN_EXPIRATION_SECONDS}

client:
    base-url: ${CLIENT_BASE_URL}
    reset-password-url: ${CLIENT_RESET_PASSWORD_URL}

logging:
    level:
        root: ${DEBUG_LEVEL}
        org:
            hibernate: error
            springframework:
                web: debug
                mail: debug

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always

spring:
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 5MB
    mail:
        host: ${EMAIL_HOST}
        port: ${EMAIL_PORT}
        username: ${EMAIL_USERNAME}
        password: ${EMAIL_PASSWORD}
        properties:
            mail:
                debug: ${EMAIL_SERVICE_DEBUG}
                smtp:
                    auth: true
                    starttls:
                        enable: true
    thymeleaf:
        check-template-location: false
    jpa:
        hibernate:
            ddl-auto: ${DDL_AUTO}
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format-sql: true
                jdbc:
                    time_zone: UTC
        show-sql: false
    datasource:
        platform: postgres
        url: jdbc:postgresql://${DB_HOST}/${DB_NAME}?user=${DB_USER}&password=${DB_PASSWORD}&sslmode=${DB_SSL}
        driverClassName: org.postgresql.Driver

cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "*"

jwt:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationInMs: ${JWT_EXPIRATION_MS}
