server:
    port: ${SERVER_PORT}
    error:
        include-message: always

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always
        monitoring:
            enabled: true

spring:
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format-sql: true
                jdbc:
                    time_zone: UTC
        show-sql: true
    datasource:
        platform: postgres
        url: jdbc:postgresql://${DB_HOST}/${DB_NAME}?user=${DB_USER}&password=${DB_PASSWORD}&sslmode=${DB_SSL}
#        url: jdbc:postgresql://${DB_LOCAL_HOST}/recruiter
#        username: postgres
#        password: postgres
        driverClassName: org.postgresql.Driver

cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "*"

jwt:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationInMs: 216000000
