  steps:
  # Build the server container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/recruiter-420314/recruiter-api:$COMMIT_SHA', '.']
  # Push the server container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/recruiter-420314/recruiter-api:$COMMIT_SHA']
  # Deploy server container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'recruiter-api'
    - '--image'
    - 'gcr.io/recruiter-420314/recruiter-api:$COMMIT_SHA'
    - '--region'
    - 'europe-west1'
  images:
  - 'gcr.io/recruiter-420314/recruiter-api:$COMMIT_SHA'


# steps:

# # Build the client container image
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t',
#     'asia-southeast1-docker.pkg.dev/recruiter-420314/recruiter-registry/recruiter-client',
#     '--build-arg', 'VITE_API_ORIGIN=https://recruiter-api-yklq5atc4q-ew.a.run.app',
#     '--build-arg', 'VITE_API_PATH=/api/v1',
#     '-f', 'client/Dockerfile', '.']

# Push the server container image to Artifact Registry
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'asia-southeast1-docker.pkg.dev/recruiter-420314/recruiter-registry/recruiter-api']
# # Push the client container image to Artifact Registry
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'asia-southeast1-docker.pkg.dev/recruiter-420314/recruiter-registry/recruiter-client']

# # Deploy server container to Cloud Run
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: gcloud
#   args: ['run', 'deploy', 'recruiter-api',
#     '--image', 'asia-southeast1-docker.pkg.dev/recruiter-420314/recruiter-registry/recruiter-api',
#     '--region', 'europe-west1',
#     '--allow-unauthenticated']

# # Deploy client container to Cloud Run
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: gcloud
#   args: ['run', 'deploy', 'recruiter-client',
#     '--image', 'asia-southeast1-docker.pkg.dev/recruiter-420314/recruiter-registry/recruiter-client',
#     '--region', 'europe-west1',
#     '--allow-unauthenticated']

# options:
#   logging: CLOUD_LOGGING_ONLY
