name: Test, Build, and Deploy

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: recruiter-test-db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup config
        run: |
          mkdir config
          echo 'spring.datasource.url=jdbc:postgresql://postgres:5432/recruiter-test-db' > config/application.properties

      - name: Build with Maven and skip tests
        working-directory: server
        run: mvn -B package --file pom.xml -DskipTests

      # - name: Install client dependencies
      #   working-directory: client
      #   run: npm ci

      # - name: Type check client
      #   working-directory: client
      #   run: npm run typecheck

      # - name: Lint client
      #   working-directory: client
      #   run: npm run lint

      # - name: Install Playwright Browsers
      #   working-directory: client
      #   run: npx playwright install --with-deps chromium

      - name: Run server
        working-directory: server/target
        env:
          DB_HOST: localhost
          DB_NAME: recruiter-test-db
          DB_USER: postgres
          DB_PASSWORD: postgres
          SERVER_PORT: 3000
          JWT_SECRET: supersecretkey
        run: java -jar recruiter-1.0-SNAPSHOT.jar 

      - name: Build front end for E2E tests
        working-directory: client
        run: npm run build
        env:
          VITE_API_ORIGIN: http://localhost:3000
          VITE_API_PATH: /api/v1

      - name: Health probe
        uses: Jtalk/url-health-check-action@v4
        with:
          max-attempts: 5
          retry-delay: 5s
          url: http://localhost:3000/actuator/health

      - name: Readiness probe
        uses: Jtalk/url-health-check-action@v4
        with:
          max-attempts: 5
          retry-delay: 5s
          url: http://localhost:3000/actuator/info
      
      - name: Test client E2E
        working-directory: client
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4.3.1
        if: always()
        with:
          name: playwright-report
          path: client/playwright-report/
          retention-days: 7
